import { Product } from './types';

export const fallbackProducts: Product[] = [
  {
    id: "prod-rental-1",
    name: "Cho Thuê Váy Dạ Hội Luxury Kim Tuyến Sang Trọng (Gói 3 Ngày)",
    category: "rental",
    price: 450000,
    originalPrice: 650000,
    rating: 4.9,
    reviewsCount: 86,
    inStock: 10,
    image: "https://images.unsplash.com/photo-1566174053879-31528523f8ae?auto=format&fit=crop&w=800&q=80",
    badge: "Thuê nhiều nhất",
    description: "Dịch vụ cho thuê đầm dạ hội thiết kế độc quyền đính kim tuyến lấp lánh.",
    specs: { "Thời gian thuê": "3 Ngày", "Size": "S, M, L", "Dịch vụ": "Giặt hấp spa" }
  },
  {
    id: "prod-rental-2",
    name: "Cho Thuê Áo Dài Thêu Tay Cổ Truyền Cao Cấp",
    category: "rental",
    price: 350000,
    originalPrice: 500000,
    rating: 4.8,
    reviewsCount: 42,
    inStock: 15,
    image: "https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=800&q=80",
    badge: "Hot Rental",
    description: "Áo dài truyền thống chất lụa tơ tằm thêu hoa sen tỉ mỉ bằng tay.",
    specs: { "Thời gian thuê": "3 Ngày", "Chất liệu": "Lụa tơ tằm" }
  },
  {
    id: "prod-fashion-1",
    name: "Đầm Lụa Satin Cổ V Dáng Xòe Sang Trọng",
    category: "fashion",
    price: 890000,
    originalPrice: 1200000,
    rating: 4.8,
    reviewsCount: 112,
    inStock: 25,
    image: "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?auto=format&fit=crop&w=800&q=80",
    badge: "Bestseller",
    description: "Thiết kế váy đầm lụa Satin cao cấp tôn dáng mềm mại, đường may tinh tế.",
    specs: { "Chất liệu": "Lụa Satin", "Form": "Chiết eo dáng xòe" }
  },
  {
    id: "prod-fashion-2",
    name: "Áo Sơ Mi Nam Lụa Ý Cao Cấp Form Slim-Fit",
    category: "fashion",
    price: 550000,
    originalPrice: 750000,
    rating: 4.7,
    reviewsCount: 78,
    inStock: 40,
    image: "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=800&q=80",
    badge: "Mới",
    description: "Áo sơ mi nam chống nhăn độc quyền, chất liệu lụa Ý mỏng nhẹ thoáng mát.",
    specs: { "Vải": "Cotton Lụa Ý", "Form": "Slim-Fit" }
  },
  {
    id: "prod-food-1",
    name: "Set Trà Sữa Ô Long Kem Trứng Nướng Premium (Combo 4 Ly)",
    category: "food_beverage",
    price: 180000,
    originalPrice: 240000,
    rating: 4.9,
    reviewsCount: 150,
    inStock: 50,
    image: "https://images.unsplash.com/photo-1558857563-b371033873b8?auto=format&fit=crop&w=800&q=80",
    badge: "Giao 30 Phút",
    description: "Trà sữa Ô long lá trà đậm đà kết hợp với lớp kem trứng nướng cháy thơm béo ngậy.",
    specs: { "Combo": "4 Ly Trà sữa 700ml", "Độ ngọt": "Tùy chọn 30%-100%" }
  },
  {
    id: "prod-food-2",
    name: "Bánh Mì Nướng Bơ Tỏi Phô Mai Pháp Handmade",
    category: "food_beverage",
    price: 120000,
    originalPrice: 150000,
    rating: 4.8,
    reviewsCount: 94,
    inStock: 30,
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80",
    badge: "Nóng Hổi",
    description: "Ổ bánh mì nướng bơ tỏi giòn rụm đẫm phô mai Mozzarella tan chảy ngậy béo.",
    specs: { "Set": "2 Ổ bánh mì lớn", "Phô mai": "Mozzarella Pháp" }
  },
  {
    id: "prod-beauty-1",
    name: "Bộ Serum Căng Bóng Dưỡng Trắng Da Hàn Quốc (50ml)",
    category: "beauty",
    price: 790000,
    originalPrice: 1100000,
    rating: 4.9,
    reviewsCount: 135,
    inStock: 20,
    image: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=800&q=80",
    badge: "Chính Hãng",
    description: "Serum chiết xuất Niacinamide 10% & Hyaluronic Acid cấp ẩm sâu, phục hồi da.",
    specs: { "Dung tích": "50ml", "Thành phần": "Niacinamide 10%, HA 2%", "Xuất xứ": "Korea" }
  },
  {
    id: "prod-beauty-2",
    name: "Son Thỏi Hiệu Ứng Lì Mịn Như Nhung Matte Lipstick",
    category: "beauty",
    price: 420000,
    originalPrice: 550000,
    rating: 4.8,
    reviewsCount: 67,
    inStock: 45,
    image: "https://images.unsplash.com/photo-1586495777744-4413f21062fa?auto=format&fit=crop&w=800&q=80",
    badge: "Hot Color",
    description: "Son lì mềm môi không gây khô ráp, lên màu chuẩn ngay từ lần quẹt đầu tiên.",
    specs: { "Tông màu": "Đỏ Đất Rạng Rỡ", "Độ bám": "8-10 tiếng" }
  }
];
